server:
  port: 8070
project:
  base-dir: ${user.dir}
  resource-dir: ${project.base-dir}/src/main/resources
log4j.configurationFile: ${project.base-dir}/src/main/resources/log4j.properties


# project.log-file: ${project.base-dir}/src/main/resources/bookstore.log

# spring.http.log-request-details: true
# JSP settings
# spring.mvc.view.prefix: /views/
# spring.mvc.view.suffix: .jsp

#REMOVE THYMELEAF CONFIGURATIONS WHEN RUNNING KUBERNETTES
# THYMELEAF Static resources for hot reloading during development
# spring.thymeleaf.cache: false
# spring.thymeleaf.prefix: file:${project.resource-dir}/templates/
# spring.resources.static-locations: file:${project.resource-dir}/static/

#------- DATABASE CONFIG -----#
spring:
  datasource:
    name: springdb
#    url: jdbc:h2:mem:${user.dir}/src/main/resources/db
    url: jdbc:h2:file:${user.dir}/src/main/resources/db/h2;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: # needed for re-hydration of h2 db
      ddl-auto: update
  h2:
    console.enabled: true
    console.path: /h2
  data:
    mongodb.host: localhost:27017
    mongodb.database: squirtledb
    rest:
      base-path: /restapi

# RedisDb configurations
# spring.redis.host: localhost
# spring.redis.port: 6379
# spring.redis.password: password

# Sentry Settings
# dsn: https://7f99bb9bacc04f63ab13330f73342485@sentry.io/1414857

# Slack Credentials
slackapp:
  id: AJ20H45GX
  clientId: 2983885750.614017141575
  clientSecret: e86a36cb76dced9628c7898aa8c241c4
  signature: 2d1596deabd596e705685c73f66506c6
